"""Generate keyboard definition as C array for embedding in firmware.

Vial expects LZMA-compressed data (XZ format). We use small dictionary (64KB)
to ensure browser-side decompression works without emscripten async issues.
"""
import lzma
import os

# Read the vial.json definition
json_path = os.path.join(os.path.dirname(__file__), 'Reference', 'vial.json')
with open(json_path, 'rb') as f:
    original = f.read()

print(f"Original JSON: {len(original)} bytes")

# Compress with XZ format (standard), small dict to avoid browser issues
compressed = lzma.compress(original,
                           filters=[{'id': lzma.FILTER_LZMA2,
                                     'preset': 1,
                                     'dict_size': 65536}])

print(f"Compressed:    {len(compressed)} bytes")

# Generate C header file
header_path = os.path.join(os.path.dirname(__file__), 'APP', 'include', 'vial_definition.h')
with open(header_path, 'w', encoding='utf-8') as f:
    f.write('/* Auto-generated keyboard definition for Vial protocol.\n')
    f.write(f' * Original: {len(original)} bytes, XZ-compressed: {len(compressed)} bytes\n')
    f.write(' * Generated by _gen_vial_def.py\n')
    f.write(' */\n\n')
    f.write('#ifndef VIAL_DEFINITION_H_\n')
    f.write('#define VIAL_DEFINITION_H_\n\n')
    f.write('#include <stdint.h>\n\n')
    f.write(f'#define VIAL_DEFINITION_SIZE {len(compressed)}\n\n')
    f.write('static const uint8_t vial_definition_data[] = {\n')

    for i in range(0, len(compressed), 12):
        chunk = compressed[i:i+12]
        hex_bytes = ', '.join(f'0x{b:02X}' for b in chunk)
        f.write(f'    {hex_bytes},\n')

    f.write('};\n\n')
    f.write('#endif /* VIAL_DEFINITION_H_ */\n')

print(f"Written: {header_path}")
