"""Generate keyboard definition as C array for embedding in firmware.

Uses same format as QMK Vial: FORMAT_ALONE + LZMA1 + preset=4.
Pads JSON with spaces so compressed size is aligned to 32-byte boundary.
This prevents trailing zeros in the last GET_DEFINITION page.
"""
import lzma
import os

# Read the vial.json definition
json_path = os.path.join(os.path.dirname(__file__), 'Reference', 'vial.json')
with open(json_path, 'rb') as f:
    original = f.read()

print(f"Original JSON: {len(original)} bytes")

# Pad to find 32-byte compressed alignment
for pad in range(0, 1024):
    padded = original + b' ' * pad
    compressed = lzma.compress(padded, format=lzma.FORMAT_ALONE,
                               filters=[{'id': lzma.FILTER_LZMA1, 'preset': 4}])
    if len(compressed) % 32 == 0:
        print(f"Padding: {pad} spaces")
        print(f"Compressed: {len(compressed)} bytes ({len(compressed)//32} pages, aligned)")
        break

# Verify roundtrip
decomp = lzma.decompress(compressed, format=lzma.FORMAT_ALONE)
assert decomp == padded, "Roundtrip failed!"
print("Roundtrip: OK")

# Generate C header file
header_path = os.path.join(os.path.dirname(__file__), 'APP', 'include', 'vial_definition.h')
with open(header_path, 'w', encoding='utf-8') as f:
    f.write('/* Auto-generated keyboard definition for Vial protocol.\n')
    f.write(f' * Original: {len(original)} bytes, with {pad}-space pad for alignment\n')
    f.write(f' * QMK-compatible ALONE+LZMA1 preset=4: {len(compressed)} bytes ({len(compressed)//32} pages)\n')
    f.write(' * Generated by _gen_vial_def.py\n')
    f.write(' */\n\n')
    f.write('#ifndef VIAL_DEFINITION_H_\n')
    f.write('#define VIAL_DEFINITION_H_\n\n')
    f.write('#include <stdint.h>\n\n')
    f.write(f'#define VIAL_DEFINITION_SIZE {len(compressed)}\n\n')
    f.write('static const uint8_t vial_definition_data[] = {\n')

    for i in range(0, len(compressed), 12):
        chunk = compressed[i:i+12]
        hex_bytes = ', '.join(f'0x{b:02X}' for b in chunk)
        f.write(f'    {hex_bytes},\n')

    f.write('};\n\n')
    f.write('#endif /* VIAL_DEFINITION_H_ */\n')

print(f"Written: {header_path}")
